### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ajthinking** [Agontuk/schema-designer#1]
I get an error when trying to install. I assume I missed something?
Running on Ubuntu 16.04.2 LTS
Node v8.2.0
npm 5.3.0
Commands used:
```
npm install
npm run-script build
```
gives
```
ERROR in ./main.js
Module build failed: Error: /home/anders/Code/schema-designer/.eslintrc:
	Configuration for rule "flowtype/require-return-type" is invalid:
	Value "[object Object]" is the wrong type.

    at validateRuleOptions (/home/anders/Code/schema-designer/node_modules/eslint/lib/config/config-validator.js:109:15)
    at Object.keys.forEach.id (/home/anders/Code/schema-designer/node_modules/eslint/lib/config/config-validator.js:156:13)
    at Array.forEach (native)
    at Object.validate (/home/anders/Code/schema-designer/node_modules/eslint/lib/config/config-validator.js:155:35)
    at Object.load (/home/anders/Code/schema-designer/node_modules/eslint/lib/config/config-file.js:559:19)
    at loadConfig (/home/anders/Code/schema-designer/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/home/anders/Code/schema-designer/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/home/anders/Code/schema-designer/node_modules/eslint/lib/config.js:260:26)
    at processText (/home/anders/Code/schema-designer/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/home/anders/Code/schema-designer/node_modules/eslint/lib/cli-engine.js:754:26)
    at lint (/home/anders/Code/schema-designer/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/home/anders/Code/schema-designer/node_modules/eslint-loader/index.js:213:21)
```
Seeing this might be just a jslint issue I commented out that rule so I could build, but I still got other errors when accessing port 3000 so I suspect I have some fundamental part missing?
Thank you and looking forward to contributing.

**Comment by Agontuk** [comment]
`flow-bin` needs to be installed globally in your system. Then use `npm start` to start the dev server.

**Comment by ajthinking** [comment]
thanks still not there though. Build successful, then get the following errors in console when serving
```
Tables.js:73 Uncaught TypeError: _jsplumb2.default.ready is not a function
    at Tables.__makeTablesDraggable__REACT_HOT_LOADER__ (Tables.js:73)
    at Tables.__makeTablesDraggable__REACT_HOT_LOADER__ (createPrototypeProxy.js:44)
    at Tables._this.makeTablesDraggable (Tables.js:46)
    at Tables.componentDidMount (Tables.js:54)
    at Tables.proxiedComponentDidMount (createPrototypeProxy.js:66)
    at eval (ReactCompositeComponent.js:264)
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at eval (ReactCompositeComponent.js:263)
    at CallbackQueue.notifyAll (CallbackQueue.js:76)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:80)
```

**Comment by Agontuk** [comment]
Make sure you're using `jsplumb 2.2.10` version. Also if you have yarn installed, use it instead of npm. It'll make sure the right versions are installed for all packages.

**Comment by ajthinking** [comment]
npm silently fails but yarn did the trick! Thats awesome. No need to change jsplumb ^2.2.10 either.
